spring.application.name=touristWebsite

    spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:39120/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ZNuFPlfPwGhowHVXobSioyDDwCNiThtc

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

file.upload-dir=uploads/