spring.application.name=touristWebsite

    spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:39120/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ZNuFPlfPwGhowHVXobSioyDDwCNiThtc

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cloudinary.cloud-name=qwml2nhz
cloudinary.api-key=527913594815121
cloudinary.api-secret=FhlNKdOq-3ilt5wj-_J2WdJqJM0

file.upload-dir=uploads/